### ISSUE TITLE
Feature request : recursive scan

### ISSUE THREAD

**Issue by kliclick** [yaser01/mkv-muxing-batch-gui#103]
Hi ! Very useful utility. I will suggest a small enhancement: make recursive scan of video folder (or at least as an option). having a structure with a subfolder for each movie and you want for example to remove all kodi information in all the movies you must move the mkv files to a single folder. Having a recursive scan you can manipulate all the movies without changing location to a single folder. 
My structure is like this:
- Videos folder
-- Movie1 (year1) 
    movie1 (year1).mkv (mkv file containt kodi info as attachment)
    movie1 (year1).jpg
-- Movie2 (year2) 
    movie2 (year2).mkv (mkv file containt kodi info as attachment)
    movie2 (year2).jpg

**Comment by yaser01** [comment]
You can just select all folders and (draga and drop) them into the videos tab :D

**Comment by brw** [comment]
I'm running mkv-muxing-batch-gui in a remote session using https://github.com/jlesage/docker-mkv-muxing-batch-gui, which can't easily open something like a file browser alongside it, so dragging and dropping doesn't really seem to be an option.

It would still be nice if there was a way to recursively scan for all the video files in a directory, or allow for multiple selections in the open folder/file dialog.
