### ISSUE TITLE
virus total flagged 32bit portable as trojan

### ISSUE THREAD

**Issue by xeolmli** [yaser01/mkv-muxing-batch-gui#105]
https://www.virustotal.com/gui/file/e70c9fd495b2e50aad3a33f45daa7d7bf0917658066a494484c4dbe68a698c76?

**Comment by yaser01** [comment]
This is a false positive indeed
I will work on this to know why this happen
I can ensure there is no malware/trojan in the app

**Comment by yaser01** [comment]
Still False Positive :D
