### ISSUE TITLE
Program doesn't work on Linux Mint (QT Platform Error)

### ISSUE THREAD

**Issue by puffin-000** [yaser01/mkv-muxing-batch-gui#106]
Hello, I like what you are doing. I can use your program via wine but your native Linux version doesn't work on my Linux Mint (Ubuntu Based Distro). When I tried to launch via terminal it gives me QT platform error that says "xbc" couldn't find. What can I do to fix it?

```bash
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Aborted (core dumped)
```

OS Info: 

<details>
  <summary>Click to expand it</summary>
  ```bash
System:
  Kernel: 5.15.0-89-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 5.8.4
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop Mobo: ASRock model: B450M-HDV R4.0 serial: <superuser required>
    UEFI: American Megatrends v: P3.70 date: 11/14/2019
CPU:
  Info: quad core model: AMD Ryzen 5 PRO 3350G with Radeon Vega Graphics bits: 64 type: MT MCP
    arch: Zen/Zen+ note: check rev: 1 cache: L1: 384 KiB L2: 2 MiB L3: 4 MiB
  Speed (MHz): avg: 3731 high: 3908 min/max: 1400/3600 boost: enabled cores: 1: 3627 2: 3862
    3: 3853 4: 3908 5: 3169 6: 3701 7: 3855 8: 3873 bogomips: 57492
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Picasso/Raven 2 [Radeon Vega Series / Radeon Mobile Series] driver: amdgpu
    v: kernel pcie: speed: 8 GT/s lanes: 16 ports: active: HDMI-A-2 empty: DP-1,HDMI-A-1,HDMI-A-3
    bus-ID: 09:00.0 chip-ID: 1002:15d8
  Device-2: Alcor Micro USB 2.0 PC Camera type: USB driver: snd-usb-audio,uvcvideo bus-ID: 3-4:2
    chip-ID: 058f:3861
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,vesa gpu: amdgpu display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96
  Monitor-1: HDMI-A-1 mapped: HDMI-A-2 model: Acer ED242QR A res: 1920x1080 dpi: 94
    diag: 600mm (23.6")
  OpenGL: renderer: AMD Radeon Vega 11 Graphics (raven LLVM 15.0.7 DRM 3.42 5.15.0-89-generic)
    v: 4.6 Mesa 23.0.4-0ubuntu1~22.04.1 direct render: Yes
   ```
</details>

I looked up on Internet to fix the problem but I can't find the solution or I'm too dumb to fix it.

**Comment by eddilara** [comment]
install ubuntu newest into a virutal machine and see if it works there
your kernal is pretty outta date on mint there

**Comment by puffin-000** [comment]
> install ubuntu newest into a virutal machine and see if it works there your kernal is pretty outta date on mint there

I Installed Ubuntu 23.10 to virtual machine and needed librarys for program via apt. It gives more error now, probably because of wayland;

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_uri_is_valid
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/home/hehe/Downloads/MKV.Muxing.Batch.GUI.x64.v2.3.Linux.Portable/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libproxy.so.1)
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_source_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so

(MKV Muxing Batch GUI:11514): GLib-GIO-ERROR **: 06:03:35.172: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/breakpoint trap (core dumped)
```
To be fair, I don't think that problem is related to older kernel version. Seems like library issue, I need to activate some kind of QT parameter to fix it but I don't know how.

**Comment by puffin-000** [comment]
Progress Update;

I was able to run program, still gives errors and crashes when I tried to input files but I understand the problem. The program tries to look and load libraries from "platforms" folder but its under "PySLide2" directory. 

I copied Qt related folders (which includes needed *platforms* folder) to main directory and be able to run the program.

> /MKV Muxing Batch GUI/PySide2/Qt/plugins

This is the directory where the folders are located. Seems like Linux support is incomplete, I will proceed to use program via wine, its more stable and usable. I will keep open the issue until problems are fixed.

**Comment by yaser01** [comment]
New Version 2.4 is more linux friendly, and read [this](https://github.com/yaser01/mkv-muxing-batch-gui/tree/2.4?tab=readme-ov-file#for-linux-users) if any problem happen again

**Comment by puffin-000** [comment]
> New Version 2.4 is more linux friendly, and read [this](https://github.com/yaser01/mkv-muxing-batch-gui/tree/2.4?tab=readme-ov-file#for-linux-users) if any problem happen again

Thank you very much, its works perfectly now. I appreciate it.

**Comment by yaser01** [comment]
@puffin-000 
You are welcome bro :D
