### ISSUE TITLE
track numbers

### ISSUE THREAD

**Issue by eddilara** [yaser01/mkv-muxing-batch-gui#11]
think this might be a bug
it seems like the video track isn't counted as the first track.......like in mediainfo...it shows the track ID's...but in the gui the audio and sub tracks are off by 1...
example...if the sub track shows as track 6 in mediainfo...in batch gui..its track 5

also...you should have a tree view (in the video tab) for the loaded files so people can get detailed info on the tracks in each file

one other thing to...would be nice if the user can specify the video file extensions.. in the video tab...example
mkv; mp4; avi

**Comment by yaser01** [comment]
First i want to say thanks for the feedback
1- For the [bug] it's not bug just the video is not counts in the [track number] i am working on edit this option to make it more clear (show language and more stuff).
2- For the tree view it's awesome will try to add it as info dialog for each video.
3- You can already specify the video file extensions [input files] and for the output it's always [mkv] as the tool called **mkv muxing batch gui**
Thanks again :)
Have a nice day :D
