### ISSUE TITLE
Virus/Malware Detection by Microsoft Defender?

### ISSUE THREAD

**Issue by perfecblue** [yaser01/mkv-muxing-batch-gui#113]
Hi, got a virus/malware warning today after installing v2.4.1 with x64 a couple days ago.  This version also shows more warnings in Virus Total's scan, is this a false positive?

https://imgur.com/a/hulHWor

![MSD01](https://github.com/yaser01/mkv-muxing-batch-gui/assets/8471025/183fce6b-131a-46ed-895d-b80553077251)
![VT01](https://github.com/yaser01/mkv-muxing-batch-gui/assets/8471025/8b81af50-866a-4232-a7e1-79aab86cff50)

Thank you!

**Comment by yaser01** [comment]
Indeed a false positive..
Those vendors are not _well known_ and not  even giving the same malware name ..
You are free to test it in windows 10 sandbox, but i can assure that this app has no malware in it
Have a nice day.

**Comment by perfecblue** [comment]
I see, thank you for the lightning reply lol, also maybe report it Microsoft so they don’t scare other ppl with it? Thanks again!
