### ISSUE TITLE
Portable Windows QT6 is reported to be infected with Wacatac.B!ml by Windows Defender

### ISSUE THREAD

**Issue by ONesterkin** [yaser01/mkv-muxing-batch-gui#115]
Subj. 
As of now decided to remove it just in case, but I really want to try this program out
Hope this will be soon resolved

**Comment by ONesterkin** [comment]
Tried to download portable versions up to 2.1 - all report to be infected. Hope it's false positive. PS running Windows 11 with stock Defender in action

**Comment by yaser01** [comment]
See this #113

**Comment by yaser01** [comment]
And furthermore..
For the new update i've submitted the file to microsoft.
![image](https://github.com/yaser01/mkv-muxing-batch-gui/assets/52576632/d10a7335-a3d1-40da-9451-7001fd612c3e)

**Comment by yaser01** [comment]
@ONesterkin 
![image](https://github.com/yaser01/mkv-muxing-batch-gui/assets/52576632/603d2f3f-ec1b-4198-960f-c30d64b02569)

**Comment by ONesterkin** [comment]
Good to know, thanks! Will proceed right away
