### ISSUE TITLE
crc filename

### ISSUE THREAD

**Issue by eddilara** [yaser01/mkv-muxing-batch-gui#14]
can you add the abilty to strip the CRC from the new filenames (anime file usually have this) after the files have been muxed...since the old crc won't be accurate anymore
and I dunno if its really nessecary...but you could add the ability to calculate the new crc of the file and add it to the filename ...like how rapidcrc does it...either that or the ability to run a command on the files once its done muxing...then we can just run rapidcrc on the files thur the cmd line

**Comment by yaser01** [comment]
I will look into this in the future updates

**Comment by yaser01** [comment]
Kindly check new version :)
