### ISSUE TITLE
Settings are stored in \AppData\Local\Temp only?

### ISSUE THREAD

**Issue by peluche-nerv** [yaser01/mkv-muxing-batch-gui#21]
Hey Yas, correct me if I'm wrong but the settings are only stored in `\AppData\Local\Temp` folder, isn't? (I searched for other folders and setting files, but can't find anything except that one)

If this is correct, you better move the settings folder to somewhere else (it would be cool to have the option to also store the settings in the program's folder), I said this because cleaning software and the OS (when restarting/closing) empties this folder, as everything inside there is considered volatile depending on if it's constantly requested or not, so when cleaning or restarting/shutting down, the settings are wiped out and it has to be configured all over again.

PS. Thanks for your work as always, and I wonder: can you make the program multilingual-able?, I want to translate it to Spanish :3

**Comment by yaser01** [comment]
All Suggestions are appreciated, and yes the setting are stored in the  `\AppData\Local\Temp` 
The temp folder usually will not be cleared for only restarting the OS 
Clean/Reset the OS will lead to such result, the reason why i didn't put it in the program's folder directly is that this folder require
admin privilege to write on it and this will be a headache for the user
There is another solution is to add an export and import setting (button) that will export current setting to file and visa versa
I guess this will be added in the next update 
For the multilingual-able I will think about it in future

**Comment by JopoJP** [comment]
Any update on that?
To export setting and import it would be realley useful.

I have about 10 audio files and 10 sub files, with naming. The process is always the sae so t import the predefined setting would speed thingsup otherwise i have to select 20x times the laguage and select the folder which is time consuming.

**Comment by yaser01** [comment]
Kindly check new version :)
