### ISSUE TITLE
default language setting

### ISSUE THREAD

**Issue by eddilara** [yaser01/mkv-muxing-batch-gui#26]
can we get a setting to have the default language set for any tracks added for audio and subs
for example...if I add audio tracks..it will automatically set the language to whatever I specify in settings

**Comment by yaser01** [comment]
Another nice feature 
I will add it in the next update 
Thanks alot

**Comment by yaser01** [comment]
isn't this an old feature ?
I added it in 2.1
you can specify default (subtitle, audio) in setting 
and after restart the app it will take effect 
or i am missing something?

**Comment by eddilara** [comment]
oh maybe you did...stupid me

**Comment by yaser01** [comment]
Can you check again so i can close this :)

**Comment by yaser01** [comment]
Kindly check new version :)
