### ISSUE TITLE
ability to download newest mkvmerge

### ISSUE THREAD

**Issue by eddilara** [yaser01/mkv-muxing-batch-gui#29]
it would be good idea to include the ability to update the mkvmerge executable without having to update the entire program...just incase you decide in the future to stop working on the program

**Comment by yaser01** [comment]
Indeed.... a very good feature, me also think about this for a while but keep delaying it for no reason 
will add it in the next update too :)

**Comment by yaser01** [comment]
Check the Readme to learn how to update mkvmerge/mkvpropedit manually
