### ISSUE TITLE
Problem in choose subtitles tracks

### ISSUE THREAD

**Issue by ThePhantom00** [yaser01/mkv-muxing-batch-gui#3]
Hi
U should make the program identify the number of tracks not a default number
cuz sometime number of tracks is more than 10 and also identify the language in each track to help to choose what track u want
Here pics
Before
1-
![image](https://user-images.githubusercontent.com/42273394/117666893-9ce5f080-b1a4-11eb-89c2-dceaa2b19f08.png)

2-
![image](https://user-images.githubusercontent.com/42273394/117667041-c3a42700-b1a4-11eb-8b37-10689cb4b59c.png)

After

1-
![image](https://user-images.githubusercontent.com/42273394/117667089-d585ca00-b1a4-11eb-9dd3-0865d4c6cadb.png)

2-
![image](https://user-images.githubusercontent.com/42273394/117667173-ec2c2100-b1a4-11eb-8d49-3bbbaf0d4d28.png)

and also u have to check that u added all languages cuz Norway not in

**Comment by yaser01** [comment]
All those suggestions are appreciated
I will work on them as soon as possible 
thanks again :D

**Comment by yaser01** [comment]
@ThePhantom00 
I need more information about the bug of  [ one of the PGS file is removed]
so I can fix it in the next update

**Comment by ThePhantom00** [comment]
as you know with dvd there are two tracks 1- full subtitle 2- sign & songs only
your program always removes that second one and now i found the it also remove Arabic subs
with no any selected settings you can see what the result
Before
![image](https://user-images.githubusercontent.com/42273394/135535607-042b5312-c320-4029-98e8-776620486cc3.png)

After
![image](https://user-images.githubusercontent.com/42273394/135535648-163e9c0b-2242-41dc-be6f-e55f98692cde.png)

**Comment by yaser01** [comment]
@ThePhantom00 
can you upload one of these files to [/drive-mega/ any good host] so i can test it and solve the problem
cause i've never seen the problem anywhere else
and a screenshot of the mux setting tab so we can solve this asap

**Comment by ThePhantom00** [comment]
i found where the problem
the problem was from track name
in MPC it shows that it's ENG track but when i opened it in MKVtool i found that it's set to Jap track, IDk how but...
i chose Jap language in "Keep Those Subtitles" section and it works
