### ISSUE TITLE
media info loading issue 

### ISSUE THREAD

**Issue by iR0lz** [yaser01/mkv-muxing-batch-gui#30]
sometimes after the finishing the muxing, and refreshing the source file with different files , the program loops in getting media info, and crashes after cancelling

**Comment by yaser01** [comment]
I will check on my side but I need a full test 
like the names of old file and new files 
and if they contain non_english letters 
any info will be useful [including screenshots]

**Comment by iR0lz** [comment]
https://user-images.githubusercontent.com/51001938/151648223-eb77aab3-6216-4830-b3b4-f10d73195a5d.mp4

**Comment by yaser01** [comment]
if you can i need full track from the start
does the problem happen always ? 
you can contact me on telegram or twitter to resolve this ASAP

**Comment by yaser01** [comment]
Kindly check new version :)
