### ISSUE TITLE
Default starting folder

### ISSUE THREAD

**Issue by eddilara** [yaser01/mkv-muxing-batch-gui#32]
not sure if this is possible..but could you add the ability to start the output folder in the same folder as the original video files
like for example....when you click on the mux setting tab....and you go to set the output folder....have the opening dialogue open in the same folder as the original video files that are loaded on the video tab

**Comment by yaser01** [comment]
there is a similar feature to this right now 
that is the dialog will open in the last folder you have opened ( in previous dialogs )
but now i think about it and yes it's more reasonable to open in the same input folder
will be added in the next one :)

**Comment by yaser01** [comment]
Kindly check new version :)
