### ISSUE TITLE
Option to not keep chapters

### ISSUE THREAD

**Issue by SkiffPL** [yaser01/mkv-muxing-batch-gui#33]
Hello! Would it be possible to disable chapters from original mkv file? Just like options for audio or subtitles?
'Only Keep Those Audios: Discard All'

I really hate chapters in mkv's and for me thats obsolete function.

Regards

**Comment by eddilara** [comment]
this is a weird request....why would you hate chapters...
they help navigate the file
are you using a good video player?

**Comment by SkiffPL** [comment]
I mainly watch all movie/episode of series or just from place where I stopped watching.
Chapters makes fast forwarding and skipping to next file weird problems on my smart TV

**Comment by vorteex** [comment]
you can do it here
https://github.com/BrunoReX/jmkvpropedit
go to the general tab and check chapters remove

**Comment by yaser01** [comment]
np...will be an add in the chapters tab as "Discard Old Chapters" just like the attachment 
Thanks for the suggestion :)

**Comment by SkiffPL** [comment]
Lovely! But maybe better option is to put this in mux settings like audio and subtitle discard option. Just saying - your decision. Thanks yaser01!

Great app, you saved me from being a clicking monkey when remuxing mkv files

**Comment by yaser01** [comment]
Kindly check new version :)
