### ISSUE TITLE
Give more options for keep/default subs (other than just lang or track#)

### ISSUE THREAD

**Issue by Darkrift411** [yaser01/mkv-muxing-batch-gui#35]
With subs, there are often multiple of the same language (such as "full dialog" + "Signs and songs") so just choosing based on lang isnt always helpful. I have recently run into a few series where the track#s dont follow a pattern (example below) and I had to basically edit ~50 episodes in batches of 3-5 that had the same track #'s

E1
Subs1 track 1: signs and songs
Subs2 track 2: full dialog

E2
Subs1 track 0: signs and songs
Subs2 track 1: full dialog

E3
Subs1 track 3: full dialog
Subs2 track 4: signs and songs

If I could enter in some sort of regex or wildcard search term such as ".*jpn.*full" (yes, I know the regex could be much better, just a basic example) and have it keep/default based on that it would solve some of these issues.

Alternately, maybe less useful, but still an improvement: If the main page listing all of the videos showed all audio/sub trcks listed for each item with a checkbox (which would be checked by default as they are already included), you would be able to go through and uncheck the items you DONT want included. This would then send them to the queue with the tracks that remain checked included and the rest removed. If you used a 3 way checkbox you could have:
unchecked = remove
checked = include
square-filled = include+default
![image](https://user-images.githubusercontent.com/10615918/152466771-aa9b473a-01e4-431d-8dcb-b515583f9a38.png)

**Comment by eddilara** [comment]
until he's able to add this feature (which I already mentioned in another post)...what I do is extract all the subs from each file....then I re-add them to the video files and remove all the old ones

**Comment by yaser01** [comment]
I am working on adding a way to select tacks by track name
Like listing all available track names according to each type (subtitle ,audio)
will this resolve the problem ?
this will make track name" Full " different from " Full2" and so on
is this ok or the regex is better?

**Comment by eddilara** [comment]
yea..being able to select based on the track name would help

**Comment by yaser01** [comment]
Kindly check new version :)
