### ISSUE TITLE
Using installed mvkmerge.exe and mkvpropedit.exe instead of supplied one

### ISSUE THREAD

**Issue by asakurato** [yaser01/mkv-muxing-batch-gui#36]
I think this is more useful (I have seen similar feature in other apps), where the app would use those files (if installed) instead of those that are supplied with it. This way, the app would always use updated MkvToolnix files, even if the app itself is not frequently updated.

#29 Is asking kinda similar thing, but I think this would be better solution (or both could be implemented, if you want).

**Comment by eddilara** [comment]
I already have a request for this basically...where someone could update mkvmerge if they wanted to outside of the app

**Comment by yaser01** [comment]
Check the Readme to learn how to update mkvmerge/mkvpropedit manually
