### ISSUE TITLE
Default Subtitle

### ISSUE THREAD

**Issue by 9Th-NightMare** [yaser01/mkv-muxing-batch-gui#38]
When I add a video with a subtitle then I add a new subtitle the default subtitle feature doesn't work

**Comment by eddilara** [comment]
you have to do that in the last tab on the right

**Comment by yaser01** [comment]
Can you explain your problem more [with media info] ? @9Th-NightMare

**Comment by 9Th-NightMare** [comment]
Ok 

First of all this is the file without merging it with the subtitle 
![image](https://user-images.githubusercontent.com/101584121/159132756-e64c54df-2306-4458-93c3-4ae7795d136a.png)


And here is the default subtitles which are there from before 
![image](https://user-images.githubusercontent.com/101584121/159132770-78beeec0-0cc2-4b1c-b774-0caadc592c37.png)


and this is the photo after merging it using the software 
![image](https://user-images.githubusercontent.com/101584121/159132798-e331ad0d-a781-4228-86be-87fe423af4eb.png)

As you can see even though I selected "Set as Default" in the software it is not selected as default

**Comment by yaser01** [comment]
This photo say [explicitly] that the arabic subtitle is set [default and forced]
![image](https://user-images.githubusercontent.com/52576632/159135086-e05835b3-a1f1-47ac-8e81-f865b5dea2fd.png)
This must be a problem from the media player i think this is MPC-HC
If so check this tab 
![image](https://user-images.githubusercontent.com/52576632/159135216-54110e5e-255d-4941-878d-f6067d5bfef6.png)
And make sure nothing is default selected

**Comment by 9Th-NightMare** [comment]
I changed the option as you mentioned but it didn't help 

![image](https://user-images.githubusercontent.com/101584121/159136180-48000f51-8b59-4648-8541-7d18465912f4.png)

**Comment by yaser01** [comment]
just leave it blank must do it 
I can't help anymore... this isn't a related problem to the software 
try https://potplayer.daum.net/ another media player [good for me]
also check the default subtitle setting [also default to be english]

**Comment by 9Th-NightMare** [comment]
Hi, 

It seems you are right. I tried using another video player (VLC) and it works. 

Thank you for everything.
