### ISSUE TITLE
Ability to remove title and track names

### ISSUE THREAD

**Issue by DanTheMobileComputerMan** [yaser01/mkv-muxing-batch-gui#39]
Please include a setting in your next version that allows any file that has a title (as displayed under the Output tab in MKVToolnNix GUI) to be removed on remux, as well as as removing a track name (as displayed under the Input tab under General options)—similar to being able to remove subtitles, chapters, and attachments.

**Comment by yaser01** [comment]
I can't see the benefit from it 
Anyway the current update is almost ready
Sorry but I will save this for the next one 
Have a nice day :D

**Comment by DanTheMobileComputerMan** [comment]
Thanks. :-) The benefit, by the way, would eliminate the need to manually delete the names when remuxing several files that all have names not wanted in the remuxes, thereby saving a lot of time for many files being remuxed at the same time together because it won't be necessary to click on several tabs first to remove them all.

**Comment by kaze5** [comment]
> Thanks. :-) The benefit, by the way, would eliminate the need to manually delete the names when remuxing several files that all have names not wanted in the remuxes, thereby saving a lot of time for many files being remuxed at the same time together because it won't be necessary to click on several tabs first to remove them all.

Use [jmkvpropedit](https://github.com/BrunoReX/jmkvpropedit/releases) for that instead, no muxing needed to edit titles or track names that so you won't lose any time.

**Comment by yaser01** [comment]
Closed cause there is alternative
