### ISSUE TITLE
Delay with eac3to

### ISSUE THREAD

**Issue by Mogured** [yaser01/mkv-muxing-batch-gui#40]
It would be amazing if you could apply delay to the audios too, with eac3to in backend

**Comment by yaser01** [comment]
There is already function "delay audio" in the app
What do you mean by using eac3to in backend?

**Comment by Mogured** [comment]
> There is already function "delay audio" in the app What do you mean by using eac3to in backend?

sorry, I mean change audio´s speed, not delay, in order to mux 25fps DVD audio (for example) into a 23.976fps video source you need to reencode audio and slowdown the speed, I usually use the eac3to tool to make this before apply delay to sync

https://www.videohelp.com/software/eac3to

eac3to can run under cli commands

**Comment by yaser01** [comment]
Can you try the following 
Add the 23.976fps video to the video tab
Add the 25fps dvd audio to the audio tab 
Then in the video tab set "Default Duration/FPS" to "25p"
Then start muxing 
And tell me about the result if the audio and video are synced or not ?

**Comment by Mogured** [comment]
sorry for the delay, I'm quite busy at work these days, but I don't forget this, try it as soon as I can and post the result, thank you very much

**Comment by yaser01** [comment]
Closed until further details
