### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by eddilara** [yaser01/mkv-muxing-batch-gui#45]
not sure if its bug or not...but the gui is still defaulting to the program files folder when choosing output folder

**Comment by yaser01** [comment]
did you choose the input [video files] from drag and drop?
In this case it can't detect the source folder probably in case you have different source folder it will get confused so it only works 
when source files are being listed from the select folder button or specify path (not drag and drop) :D

**Comment by eddilara** [comment]
yea from drag and drop....ok so thats the problem....thought it was a bug or something

**Comment by yaser01** [comment]
Not a problem :)
