### ISSUE TITLE
Cannot run on Linux

### ISSUE THREAD

**Issue by Pemicope** [yaser01/mkv-muxing-batch-gui#47]
Hello, I can't run the application on Linux.
I get the following error:

```
qt.qpa.plugin:` Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

`Aborted`

I have installed everything needed as described in the instructions. Not sure what to do...
I'm using Zorin OS latest version, it's based on Ubuntu 20.04

**Comment by yaser01** [comment]
sorry for that, i will try it today on Zorin OS and will try figure a solution :)

**Comment by yaser01** [comment]
I've tried it on Zorin OS 16.1 
![Screenshot from 2022-05-04 13-29-29](https://user-images.githubusercontent.com/52576632/166693304-3f395d3c-f6d3-4eb9-8406-07d061ceb6de.png)

![Screenshot from 2022-05-04 13-31-46](https://user-images.githubusercontent.com/52576632/166692880-742cdfc7-9ecc-4bed-badd-40eef268fd32.png)
and it works perfectly 
did you try 
**sudo apt-get update** 
Can you give me more information about the OS Version?

**Comment by Pemicope** [comment]
Everything is updated. I'm using the same version as you, I honestly don't know what's causing this...
Anyway, thank you for your time. I'll try to figure it out. :)

**Comment by yaser01** [comment]
Try this  in the terminal :
**export QT_DEBUG_PLUGINS=1**
Then try to running the app, does the error updated?

**Comment by Pemicope** [comment]
Now it gives me this error:

QFactoryLoader::QFactoryLoader() checking directory path "/home/user/Documents/Aplicações/MKV Muxing Batch GUI/platforms" ...
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted

**Comment by yaser01** [comment]
can you try to put the app folder outside folder "Aplicações"
like in the Documents directly like this "/home/user/Documents/MKV Muxing Batch GUI

**Comment by yaser01** [comment]
NICE :D
Have a great day/night too :)
