### ISSUE TITLE
Feature request : make an option to overwrite source files when starting the batch

### ISSUE THREAD

**Issue by Kromasm** [yaser01/mkv-muxing-batch-gui#49]
Everything is in the title ! It will save time. ^^

**Comment by yaser01** [comment]
So simple :)
Coming soon...

**Comment by eddilara** [comment]
if your gonna add this...you better have a confirmation dialogue for the user to be absolutely sure they wanna basically delete the old files

**Comment by yaser01** [comment]
@eddilara Absolutely there will be a confirmation dialog .
btw thanks for the feedback :)

**Comment by yaser01** [comment]
Try 2.4 Update :D

**Comment by Kromasm** [comment]
Thank you for the update ! Wonderful software ! :-)
