### ISSUE TITLE
Feature request : Multi-Folder File Font Attachments

### ISSUE THREAD

**Issue by jazmac** [yaser01/mkv-muxing-batch-gui#51]
So basically as far as I can tell when adding new font attachments, you only have the ability to select one folder containing all the fonts and mux them into every file in the queue.

With a lot of subtitles though, each video file can often have its own unique set of fonts which may have some cross-over with other files but not necessarily the exact same set of fonts (this happens a lot with anime). Now I know I could just mux all the fonts I intend to use in a set into every file regardless if it gets used or not but it would be a lot cleaner (and just generally all around better practice) and avoid any potential issues with font attachment bloat.

Essentially what I'm requesting is to have a similar setup as the subtitle tab where I can have a list of folders that contain fonts "line up" with the video files and only the folder that is parallel to it will be muxed into that specific video, if that makes sense.

Here's a [link](https://i.imgur.com/V2yMwKH.png) to an example of the kind of folder setup I typically have to hopefully illustrate the problem.

**Comment by yaser01** [comment]
Thanks for the extreme explanation 
I don't know but I think this is over in some sense.
But I will give it a try in the next update :)

**Comment by eddilara** [comment]
fonts are usually fairly small...does it really matter if you mux all of the fonts into every file
thats what I normally do
and if you have a big font file you need in only 1 or 2 files...just leave them outta the muxing..and just use mkvtools to mux just those fonts into the 1 or 2 files you need them in

**Comment by yaser01** [comment]
Fair point @eddilara 
But maybe, I will make something like expert mode to allow something like that
Maybe in the future :)

**Comment by enchained** [comment]
Did not test the dev branch yet, so not sure how this is implemented, but it will be very useful for me too. I often add fonts from multiple folders one by one in the mkvtoolnix gui. I think it also cross-checks the fonts with all previously added ones, and asks if I want to skip those. I hope that a duplicate check will be integrated into this new feature.

**Comment by yaser01** [comment]
Try 2.4 Update :D

**Comment by jazmac** [comment]
> Try 2.4 Update :D

I will! I never expected this to be implemented. Your efforts are much appreciated.
