### ISSUE TITLE
Allow Source Folder from Network Drive

### ISSUE THREAD

**Issue by tangentThought** [yaser01/mkv-muxing-batch-gui#52]
I have a network drive where all of my source files are located, but the program only seems to read my local drives.

**Comment by yaser01** [comment]
How to do you read the files the network drive ?
Screenshot may help :)

**Comment by Gladosx9** [comment]
Same here, the program can load videos from my network drive but it wont export to it, it says "it's not a valid path"

**Comment by yaser01** [comment]
can you just gave me some screenshots ? @Gladosx9

**Comment by Gladosx9** [comment]
> Can you just gave me some screenshots ? @Gladosx9

Update: no worries, it's just that the network path \\ABC\AAAA is not being recognized instead we can just use MS-DOS path Z:\
Thanks for this handy program it 's time-saving, helping me a lot tbh

It will be be great if there is an option for loading from subfolders .

**Comment by yaser01** [comment]
You are welcome
About the subfolders thing you can open another issue for it
