### ISSUE TITLE
Change order of existing tracks

### ISSUE THREAD

**Issue by janaxhell** [yaser01/mkv-muxing-batch-gui#53]
I have a TV that always plays the first audio track, no matter which is flagged as Default, so in rare cases I have to remux files without adding anything new, but just move to top the audio track I want as Default.
This "Mux at top" option is present in the GUI, but it seems to be working only with new added/imported tracks, not already existing tracks. I have  tried "Usual muxing" enabling "Mux at top" for the track I want, but nothing changes, the output files are exactly as the input. 
Is there any way to just move existing audio tracks inside MKVs?

**Comment by yaser01** [comment]
I see for now you have to extract them and then remux again  with option  "Mux at top".
This will work as temp solution

**Comment by Xcl4m4t10n** [comment]
I came here to propose the same, so I'm happy that somebody's done it already :D.

**Comment by yaser01** [comment]
Try 2.4 Update :D

**Comment by janaxhell** [comment]
Hi, just tried 2.4. I see the option "Mux after [At Top]" etc, but after setting my preferred languages in the Options (Italian, English, Japanese) for both audio and subtitles, the GUI lets me only choose between English and Arabic. I have obviously restarted the app after changing the options. So I cannot try the Mux at Top function because I cannot choose the track I want.

**Comment by yaser01** [comment]
Noticed..
Will be fixed ASAP

**Comment by yaser01** [comment]
@janaxhell 2.4.1 is out 
Waiting for your feedback...

**Comment by janaxhell** [comment]
Ok, 2.4.1 partially works, I can now choose language from GUI, but it only sets it as default, it does not mux it "at top", it just changes the flag. On windows this works fine, but on TV usually the first track is chosen, no matter the flag, so If the track I want to hear is not physically the first, but only flagged as default, I won't hear it, but whatever comes first.

Also further feedback on GUI: I find a bit confusing to have audio settings in both Audios and Mux Setting tabs. Also each time I leave Mux Settings tab, it forgets my settings. Audios tab retains my settings, Mux Settings tab doesn't. Not a problem, you just set it last then mux, but I think it's a bug.

**Comment by yaser01** [comment]
Can you give me a media info before and after with screenshots of selected options you make in the app. because on my side it does really **mux it at top**.

> I find a bit confusing to have audio settings in both Audios and Mux Setting tabs.

You probably confused that the setting in `Audio Tab` concerns the **_new_** added audio to the source files.
But the setting in `Muxing Tab` concern the audios that are _**already**_ in the source video files.
maybe it's not **too** obvious... maybe i will work on something to make it more _"clear"_

**Comment by janaxhell** [comment]
> You probably confused that the setting in Audio Tab concerns the new added audio to the source files.
> But the setting in Muxing Tab concern the audios that are already in the source video files.

That's the problem. I don't want to add new audio tracks, I want to change order to those existing, and that option is not available in the Mux Setting tab. If you say Audios tab only works on newly added tracks, it has no effect in my case. 
From Mux Setting tab I can only set the track I want to Default, but that only changes the flag as I mentioned.

**Comment by janaxhell** [comment]
I have seen it now, but it does the same: it sets a track to default, but does not move it to top position. I have tried to drag it, but it does not move.

**Comment by yaser01** [comment]
@janaxhell You haven't see this ?
![image](https://github.com/yaser01/mkv-muxing-batch-gui/assets/52576632/9fb7336a-15e8-4767-8f09-3bccf2ef1774)

**Comment by janaxhell** [comment]
Ahh, yes, I see it now, thanks. It works fine, the tracks are moved where I want. I have to say that the GUI is not exactly intuitive. I would add at least an UP/DOWN button beside the tracks. Graphic interfaces should be.. "graphic".  :)

**Comment by yaser01** [comment]
I thought about this.. but didn't like it when i add it 
So maybe another design for next updates.. we will see :D
