### ISSUE TITLE
[Feature Request] Just some suggestions

### ISSUE THREAD

**Issue by vitormathews** [yaser01/mkv-muxing-batch-gui#54]
- Add a exit warning, to prevent from accidentaly closing the window and losing all the selections made.
- Remember Last Session, or keep the history of the previous jobs, like MKVToolNix does, so if you later found any error in the output, you can just fix it and remux everything again, as long as the source files are still in the same folders.
- Add option to change track position of selected subtitles (or better: to add a new track in place of a existing track by its name), and also an option to mux new subs in any desired position of the existing video, not just top/bottom.
- Option to "select all" in "Only keep those subtitles"
- And of course: dark mode 😅

**Comment by vitormathews** [comment]
Thanks for the reply! XD

> 4. you don't need to "select all" in "Only keep those subtitles"... if you want to keep all subtitle just don't activate the option

And about the point 4, I know that if I wanna keep all subs I can do this, but a Select All option would be very useful when you have a lot of tracks and just want one of them to be removed, so you could just Select All and uncheck the one you don't want anymore.

**Comment by yaser01** [comment]
Note 3: I am forced to drop this because this is batch muxing [files doesn't have to have the same number of tracks... ]
Note 2: Can't promise alot
Other notes are being working on :D

**Comment by vitormathews** [comment]
> Note 3: I am forced to drop this because this is batch muxing [files doesn't have to have the same number of tracks... ]

Wouldn't it be available only if all the files have the same number of tracks? It's a pain when I need to add a new subtitle between others already present and I have to go around selecting the folders of all the other subtitles again.

**Comment by yaser01** [comment]
So i understand you want to mux new subtitle in a specific order maybe become 2nd subtitle or third .. and so  on ?

**Comment by vitormathews** [comment]
> So i understand you want to mux new subtitle in a specific order maybe become 2nd subtitle or third .. and so on ?

Yes. Taking this as an example, in the future I will have to add new tracks in Portuguese, so I would just select the folder that contains the subtitles and choose them to be added as the 6th track.
![image](https://github.com/yaser01/mkv-muxing-batch-gui/assets/51209382/a0a77b44-fabb-4c84-bf7b-d3203af7bf4e)

**Comment by yaser01** [comment]
I will think of a good way to do this

**Comment by yaser01** [comment]
Try 2.4 Update :D

**Comment by vitormathews** [comment]
> Try 2.4 Update :D

Wooooooooow FINALLY! 😍
I will test the new version soon!

**Comment by yaser01** [comment]
@vitormathews waiting your feedback :D

**Comment by KonoVitoDa** [comment]
Hello, sorry for the late reply. I've finally had the opportunity to test the new release properly, not just by giving a quick peek at the new UI as I did before, and here I am to give my feedback:
- I absolutely loved the new dark mode, my eyes thank you!
- The exit warning is very useful, but I'd also like it to remain active after I finish muxing, as there's the chance the user notices some mistake aftewards and needs to fix it by just doing minor changes on the selections made.
- Besides that, I've also noticed that the new _Mux After_ only has the options 1st and 2nd subtitle, so I couldn't even test it properly when I had the opportunity, as I wanted to mux a sub after the 5th one.
- A bug: I couldn't use quotes _""_ in a track name, this error occurred:
![image](https://github.com/yaser01/mkv-muxing-batch-gui/assets/51209382/214c90f5-4588-452a-8b47-6cb2d3fe0eae)
That's something I could do with no problems in the older versions.

And some ideas for new features I had while using it (should I open a new issue for them?):
- Change delay for specific files only, no the whole track.
- Check/uncheck feature for tracks, not just video; and the ability to select multiple of them to check/uncheck/delete or whatever, and a _Clear All_ option too.
- Apply delay to all tracks.
- Swap the position of existing tracks, or add a new track after an existing one. The _Mux After_ option would already do the trick, but this way it would be more intuitive.
- Let a track to be matched with other than the first video.
- Someone shoul've already asked for this one: mux different video files, like you can do on MKVToolnix, selecting the tracks you want in the final MKV between the two sources. For example, I had a 15-episode anime and would like to just replace its video/audio encode by a new one.
- Delay for chapters, but keeping the first chapter start time to 00:00:00.000.
