### ISSUE TITLE
Thumbnail option

### ISSUE THREAD

**Issue by ThePhantom00** [yaser01/mkv-muxing-batch-gui#57]
i hope u add tap for adding thumbnails
- add thumbs like subs
or
- one thumb for all files

**Comment by yaser01** [comment]
I like it but what do you think is the best 
To add one file to all files or make it like subs?

**Comment by yaser01** [comment]
I like it but what do you think is the best 
To add one file to all files or make it like subs?

**Comment by ThePhantom00** [comment]
both😂

**Comment by yaser01** [comment]
OK :D

**Comment by ThePhantom00** [comment]
@yaser01 
update for this enhancement
auto resize image if exceeded the dimension limit

**Comment by yaser01** [comment]
is this still wanted ?
what is the dimension limit?
and why can't you add thumb with attachments?

**Comment by ThePhantom00** [comment]
@yaser01 
first thing first
welcome back bro❤ i hope u r doing well 🙏🏻❤
Sec
1.  **is this still wanted?**
yup

2.  **what is the dimension limit?**
look here [https://www.matroska.org/technical/attachments.html](cover in MKV)

3. **and why can't you add thumb with attachments?**
i tried but it's not recognized or not appearing

**Comment by yaser01** [comment]
Thanks for your worries bro❤
Did you try to rename cover name as mentioned?
![image](https://user-images.githubusercontent.com/52576632/237060935-6aa82b7c-bb24-40b9-b210-5500ad637603.png)
And then muxing it

**Comment by ThePhantom00** [comment]
Yup
Tried all

**Comment by yaser01** [comment]
awkward this works with me "cover.png"
Did you choose "Usual Muxing" or "Fast Muxing" when testing this

**Comment by yaser01** [comment]
Can i get a full mediainfo of input video and output video

**Comment by ThePhantom00** [comment]
lol it works now XD
now here is my request 👉🏻👈🏻
i want a tab like subs for covers cuz we make a different cover for each episode and the program rename the file to cover at muxing

**Comment by yaser01** [comment]
Wait why did it worked NOW :D 
What changed did you make?
For your request you mean to have a attachment folder for each video?

**Comment by ThePhantom00** [comment]
Just changed the dimensions again and worked XD

For my request, yeah
Cuz i have a different thumbnail for each video

**Comment by yaser01** [comment]
Ok what i will do is adding a attachment folder for each video just like the old subtitle tab

**Comment by ThePhantom00** [comment]
Maybe a tab like sub but you can activate it from settings
And also it rename it to "cover" cuz i gonna add them like subs

**Comment by yaser01** [comment]
I will see  :D

**Comment by yaser01** [comment]
Try 2.4 Update :D
