### ISSUE TITLE
Req: Don't duplicate existing attachments

### ISSUE THREAD

**Issue by nx6** [yaser01/mkv-muxing-batch-gui#58]
I had a folder of files and some of the episodes had all required fonts already for the subtitle script, but some did not. I had figured out what fonts I was missing but not which of the files needed them, and which did not. So I remuxxed the entire directory, adding the font attachments. This results in some files having more than one copy of some font attachments.

When I do muxing manually and try to add a font that is already there MKVToolnix will say something and I can tell it to skip adding the file again. Would be nice if this GUI recognized this and didn't add the file when it already exists in the file. "Discard Old Attachments" would only work here if I didn't want to keep anything existing and requires all files in the batch use the same attachment group (which they may not apply depending on typesetting).

**Comment by eddilara** [comment]
until he adds this...what I do is...collect all the fonts the files need....then discard all the old fonts..and add the complete set of fonts to every file...this does result in a tiny bit of bloat in the files...but most fonts are pretty small

**Comment by yaser01** [comment]
Thanks for the very nice explanation 
I can add a checkbox that will skip muxing old fonts that are already in the file 
Is this will be enough?

**Comment by nx6** [comment]
Yes. That is what I am looking for, the system to see a attachment is already present and not re-add it.

**Comment by yaser01** [comment]
Nice, i will add it in the next update, which will be released in this year [hopefully] :)

**Comment by yaser01** [comment]
Try 2.4 Update :D
