### ISSUE TITLE
Missing Files MkvMerge File

### ISSUE THREAD

**Issue by michaeljhkim** [yaser01/mkv-muxing-batch-gui#59]
so I am trying to run this on pop os latest version, and it keeps giving me that same error message every time I open the app. IDK why, because I installed mkvtoonix.

**Comment by yaser01** [comment]
Try to copy **mkvmerge** and **mkvpropedit** from mkvtoonix folder and put them into Tools Folder in this path:
...\MKV Muxing Batch GUI\Resources\Tools\[You must find a folder with your system core]
Tell me if this not help :)

**Comment by michaeljkkim** [comment]
> 

it did not work. It just showed the same

**Comment by akovia** [comment]
I ran into the same issue and figured out how to work around it at least temporarily. Since this is not being updated, I needed to point to the current versions of the files on my system by symlinking to them.

I started by following the directions here, except I backed up my Tools folder and symlinked my system files into a new `Tools/Linux` folder instead.

```
sudo ln -s /bin/mkvpropedit ~/bin/MKV\ Muxing\ Batch\ GUI/Resources/Tools/Linux/
sudo ln -s /bin/mkvmerge ~/bin/MKV\ Muxing\ Batch\ GUI/Resources/Tools/Linux/
```

When that didn't work, I launched the program from the commandline so I could see each error to see if I could fix each issue.
```
$ ./MKV\ Muxing\ Batch\ GUI 
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvpropedit: error while loading shared libraries: libboost_filesystem.so.1.71.0: cannot open shared object file: No such file or directory
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvmerge: error while loading shared libraries: libboost_filesystem.so.1.71.0: cannot open shared object file: No such file or directory
```
I don't have that version on my system so I symlinked to my current version.

```
$ locate libboost_filesystem.so
/usr/lib/libboost_filesystem.so
/usr/lib/libboost_filesystem.so.1.81.0

$ sudo ln -s /usr/lib/libboost_filesystem.so.1.81.0 /usr/lib/libboost_filesystem.so.1.71.0
```

Now when I launch the program I get different errors.

```
$ ./MKV\ Muxing\ Batch\ GUI 
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvpropedit: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvpropedit)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvpropedit: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvpropedit)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvpropedit: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libmatroska.so.7)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvpropedit: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libebml.so.5)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvpropedit: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libpugixml.so.1)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvpropedit: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/libfmt.so.9)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvpropedit: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libfmt.so.9)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvpropedit: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/libQt6Core.so.6)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvpropedit: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libQt6Core.so.6)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvpropedit: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /usr/lib/libQt6Core.so.6)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvpropedit: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libicuuc.so.72)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvmerge: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvmerge)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvmerge: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvmerge)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvmerge: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libmatroska.so.7)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvmerge: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libebml.so.5)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvmerge: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libpugixml.so.1)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvmerge: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/libfmt.so.9)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvmerge: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libfmt.so.9)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvmerge: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/libQt6Core.so.6)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvmerge: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libQt6Core.so.6)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvmerge: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /usr/lib/libQt6Core.so.6)
~/bin/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvmerge: ~/bin/MKV Muxing Batch GUI/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libicuuc.so.72)
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 524, resource id: 17908404, major code: 40 (TranslateCoords), minor code: 0
```

Lots of errors, but apparently it's all from a single file. This time I symlinked the current file into the program's directory and backed up the existing.

```
$ locate libstdc++.so
/usr/lib/libstdc++.so
/usr/lib/libstdc++.so.6
/usr/lib/libstdc++.so.6.0.30
/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/libstdc++.so
/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/libstdc++.so.6
/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/libstdc++.so.6.0.28
/usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/libstdc++.so
/usr/lib32/libstdc++.so
/usr/lib32/libstdc++.so.6
/usr/lib32/libstdc++.so.6.0.30

$ mv ~/bin/MKV\ Muxing\ Batch\ GUI/libstdc++.so.6.0 ~/bin/MKV\ Muxing\ Batch\ GUI/libstdc++.so.6.0~

$ sudo ln -s /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/libstdc++.so.6.0.28 ~/bin/MKV\ Muxing\ Batch\ GUI/libstdc++.so.6.0
```

After that, it launched and is working perfectly so far. No idea if/when an update will break it, but will keep trying to symlink current files until it stops working.

Hope this helps someone. 
This program is fantastic and glad I found it.
Hopefully the author returns and updates this.

**Comment by Fujiwara-Chika** [comment]
same issue on fedora37 wayland
` GDK_BACKEND=x11 ./MKV\ Muxing\ Batch\ GUI                                       22:10:19
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Gtk-Message: 22:10:21.154: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:10:21.154: Failed to load module "pk-gtk-module"
Gtk-Message: 22:10:21.154: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:10:21.154: Failed to load module "pk-gtk-module"
/home/chika/Downloads/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvpropedit: error while loading shared libraries: libboost_filesystem.so.1.71.0: cannot open shared object file: No such file or directory
/home/chika/Downloads/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvmerge: error while loading shared libraries: libboost_filesystem.so.1.71.0: cannot open shared object file: No such file or directory
\/home/chika/Downloads/MKV Muxing Batch GUI/Resources/Tools/Linux/mkvmerge: error while loading shared libraries: libboost_filesystem.so.1.71.0: cannot open shared object file: No such file or directory
QThread: Destroyed while thread is still running
Fatal Python error: Aborted

Current thread 0x00007fa35ed22040 (most recent call first):
  File "packages/Tabs/VideoTab/VideoSelection.py", line 368 in update_files_with_drag_and_drop
  File "packages/Tabs/VideoTab/Widgets/VideoTable.py", line 64 in dropEvent
  File "main.py", line 52 in run_application
  File "main.py", line 80 in <module>
fish: Job 1, 'GDK_BACKEND=x11 ./MKV\ Muxing\ …' terminated by signal SIGABRT (Abort)`

**Comment by Fujiwara-Chika** [comment]
`export QT_QPA_PLATFORM=wayland`
`ln -s /usr/lib64/libstdc++.so.6 libstdc++.so.6 `
`ln -s /usr/bin/mkvpropedit Resources/Tools/Linux/mkvpropedit`
`ln -s /usr/bin/mkvmerge Resources/Tools/Linux/mkvmerge`

it works on fedora

**Comment by yaser01** [comment]
Is this solved?
