### ISSUE TITLE
muxing stuck 

### ISSUE THREAD

**Issue by iR0lz** [yaser01/mkv-muxing-batch-gui#6]
some muxing stuck at some point 
![image](https://user-images.githubusercontent.com/51001938/124451464-76a09380-dd96-11eb-8b93-1212090502b3.png)

**Comment by yaser01** [comment]
please first install the new release 1.0.5 from here https://github.com/yaser01/mkv-muxing-batch-gui/releases
and if the problem still exists you can upload the folder
"%TEMP%MKV Muxing Batch GUI" (Just Copy this and paste it in path section in the windows explorer)
this folder contains all logs.[don't forget to zip the folder before upload]
so I can detect the problem probably
another question is this problem happen when muxing specific files or just random
and if it's with specific file ,can you upload the media-info for it ( maybe it's file encoding problem)

**Comment by yaser01** [comment]
@iR0lz  can you give me the current status of this bug after trying the above solution

**Comment by yaser01** [comment]
will close this [no response for long time ]
