### ISSUE TITLE
[Help] Is there a way to launch mkv-muxing-batch-gui in MacOS

### ISSUE THREAD

**Issue by valentinfltv** [yaser01/mkv-muxing-batch-gui#61]
Hello @yaser01,
I'd like to say thank you for your efforts and this amazing utility - it saves a lot of time when the audio track comes separate from video files (common thing for anime series)! 
With Windows it runs great, yet recently changed PC to Mac(intel) and I'm not able to launch app anymore.
When double click the Unix executable file it gives an error:
```
Last login: Sat Aug 27 10:02:34 on console
/Users/vimini/Downloads/MKV\ Muxing\ Batch\ GUI/MKV\ Muxing\ Batch\ GUI ; exit;
vimini@Vivis-Mac-mini ~ % /Users/vimini/Downloads/MKV\ Muxing\ Batch\ GUI/MKV\ Muxing\ Batch\ GUI ; exit;
zsh: exec format error: /Users/vimini/Downloads/MKV Muxing Batch GUI/MKV Muxing Batch GUI

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```
I have python3, recent pyside2, psutils installed.
Is there a way to troubleshoot and run the app on Mac?

**Comment by eddilara** [comment]
https://www.howtogeek.com/187359/5-ways-to-run-windows-software-on-a-mac/

**Comment by yaser01** [comment]
Is this still a problem @valentinfltv
