### ISSUE TITLE
Removing Video to get MKA files

### ISSUE THREAD

**Issue by cybee2** [yaser01/mkv-muxing-batch-gui#62]
Often I need to replace the audio for a series using a 2nd set that has similar video but different audio codecs. The 1st set's audio is unreadable for my TV but I want the video quality basically.
So I remove the video from the 2nd set and put it into the 1st set as MKA using MKV Muxing Batch GUI

Can we have an option to Not Keep the video too? Or is there an alternative way of doing this^?

I make do with renaming the 2nd set with MKA and putting it in with the Batch GUI, ending with 2 videos on 1 file but I don't have to mux every single one. But the size is worrying.

**Comment by cybee2** [comment]
Just to add,
I make do with renaming the 2nd set with MKA anyway, and ending up with 2 videos in 1 file so I don't have to mux every one. But the size is worrying

**Comment by eddilara** [comment]
use mkvcleaver to extract video or audio

**Comment by yaser01** [comment]
I can see the problem.
Did mkvcleaver solve the issue as @eddilara suggested ? @cybee2

**Comment by cybee2** [comment]
Yep. I remember using that for subs years ago. I couldn't remember the name.
