### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by PHM2D** [yaser01/mkv-muxing-batch-gui#63]
Hello.

I cannot thank you enough for this super great gui. I have downloaded the latest version and replaced the resources of mkvmerge , mkvpropedit with the newer version and everything works fine.

I just have one request: please add dark theme to your great gui.

Thank you so much.

**Comment by yaser01** [comment]
You are welcome bro :D
I will try to add this :)

**Comment by yaser01** [comment]
Try 2.4 Update :D
