### ISSUE TITLE
Delete option

### ISSUE THREAD

**Issue by jimlynnjulian** [yaser01/mkv-muxing-batch-gui#64]
A suggestion rather than an issue.
Include an option to deposit in the same folder and delete the old version.

**Comment by eddilara** [comment]
a better option would be to auto create a folder inside the work folder...this is just incase someone makes a mistake with removing the old files

**Comment by yaser01** [comment]
Thanks for the suggestion 
Can be added as an option to save up space while muxing...
@eddilara I know it will be critical but it can have also a pop up to confirm the option..

**Comment by jimlynnjulian** [comment]
My reason is I have fifteen terabytes on ten drives that I need to convert to mkv. I do not have the luxury of saving original files. This does bring up a question of error response. I discovered a file that  lost data during download and would not play.
   What happens when a dysfunctional file is encountered? Does the app hang? Are there any pre-checks on the file performed?
Closing this issue.

**Comment by jimlynnjulian** [comment]
Closing, again.
