### ISSUE TITLE
Dysfunctional files and pre-checks

### ISSUE THREAD

**Issue by jimlynnjulian** [yaser01/mkv-muxing-batch-gui#66]
I discovered a file that  lost data during download and would not play.
   What happens when a dysfunctional file is encountered? Does the app hang? Are there any pre-checks on the file performed? This could be important in bulk processing if the computer is left unattended.

Again, more a question than an issue.

Thank you.

**Comment by jimlynnjulian** [comment]
I think I'll wait on a response.

**Comment by yaser01** [comment]
Try it and you will discover it :)
There is a option to stop muxing when error occurs try to check it and mux this corrupted  file and see what will happens and report to me :)
