### ISSUE TITLE
Feature request: support adding forced subtitle in addition to non-forced subtitle to video

### ISSUE THREAD

**Issue by markmarz** [yaser01/mkv-muxing-batch-gui#67]
Hi,

I'm new to your utility, so maybe I'm missing this. I don't see a way to add both a forced and non-forced subtitle to a single video file, never mind doing the same in a batch for multiple videos. It appears you can have a single subtitle either forced or not per video.

Some files in the batch will have only a single, non-forced subtitle, some have both.

Thanks,
Mark M.

**Comment by eddilara** [comment]
until he can add this
what I do is just process the files twice....do it once for forced...then do it again for another sub

**Comment by markmarz** [comment]
> until he can add this what I do is just process the files twice....do it once for forced...then do it again for another sub

Thanks for the tip.

**Comment by yaser01** [comment]
Actually can do this with current version 
you can have two subtitle tab one with subtitle to be forced
and the other subtitle tab with the subtitle not to be forced
is this what do you mean ?
or you want to have more than one subtitle to be forced in the same video ?

**Comment by yaser01** [comment]
@eddilara np bro 
closing this until further information given
