### ISSUE TITLE
installation in the default mka program for audio and the inability to drag a file from explorer into the program

### ISSUE THREAD

**Issue by AdventurerRussia** [yaser01/mkv-muxing-batch-gui#68]
I noticed that by default only aac is enabled for audio in the program, it's very strange when many tracks in the hands are stored in mka. 
of course, there are no difficulties with enabling this format in the settings, but it's still worth improving the default settings, 
I just don't see any reason why all formats are disabled by default, it only causes minor difficulties when working with the program for the first time, since you have to enable all these formats in the settings.
There is also a lack of functionality for dragging files or even folders from the file explorer to the file selection window in your program.
Well, I am reasoning from the position of an ordinary user, so that it is convenient for a person to interact with your program.

**Comment by yaser01** [comment]
closed because no further info
