### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Marco-9456** [yaser01/mkv-muxing-batch-gui#70]
Is it possible to add the following :
1. An option that renames the `video track name` same as the `file name`.
2. also the same option for `subtitle` and `audio` tracks

That would be great to have :)

**Comment by yaser01** [comment]
Do you think this option have to be like all in one  [one check to rename all video/subtitles/audios track name to the corresponding file name]
or option for each one separately option for [video/subtitle/audios]

**Comment by Marco-9456** [comment]
Welcome back brother,

The second option is more sensible. A possible use case would be when a user has subtitle files where the translator credits have been removed, but still wants to acknowledge them by naming the subtitle track with the translator or translation group name.

**Comment by yaser01** [comment]
Thanks Bro  :D
Ok I will look into this soon

**Comment by yaser01** [comment]
Try 2.4 Update :D

**Comment by Marco-9456** [comment]
> Try 2.4 Update :D

Love the new update, well done brother.
