### ISSUE TITLE
how to remove track name

### ISSUE THREAD

**Issue by PitchAbyss** [yaser01/mkv-muxing-batch-gui#72]
![image](https://user-images.githubusercontent.com/13099434/200142015-eee56c31-156c-4aaf-8cbf-b82bd727e37d.png)

please tell

**Comment by eddilara** [comment]
doesn't have that feature yet
if he adds the cmd feature I requested in the next version...then you will be able to

**Comment by ifelixculpa** [comment]
> doesn't have that feature yet
> if he adds the cmd feature I requested in the next version...then you will be able to

Thankuu sir. Lets hope he does

**Comment by yaser01** [comment]
You want to rename track name of old tracks ?
@ifelixculpa

**Comment by ifelixculpa** [comment]
> You want to rename track name of old tracks ?
> @ifelixculpa 

Ofcourse sir

**Comment by yaser01** [comment]
ok will look into this :D

**Comment by yaser01** [comment]
Try 2.4 Update :D
