### ISSUE TITLE
Feature request - change framerate

### ISSUE THREAD

**Issue by slamdance** [yaser01/mkv-muxing-batch-gui#77]
Would be great to have the option in MKV Muxing Batch (already within MKVmerge) to change the default framerate/duration.

I have to this often in case of PAL 25fps DVD and Blu-ray sources to correct the playback speed to 23.976fps. (Otherwise you can notice certain films and series sound sped up, which they are.)

Certain audio tracks can also be adjusted using the "stretch by" field in MKVmerge, while others have to be done manually with something like eac3to. In any case, remuxes currently must be done one file at a time to be able to change these fields. Being able to remux in bulk would be a timesaver!

**Comment by yaser01** [comment]
Option [Default Duration/FPS] already in videos tab
![image](https://user-images.githubusercontent.com/52576632/237000889-8e2212b3-ae7b-406e-b74f-af4c0c4acc56.png)
Or you want something different?

**Comment by yaser01** [comment]
This will be closed cuz need more information
