### ISSUE TITLE
Request - Add Feature - Input->Subfolders ; Output -> Same As Source

### ISSUE THREAD

**Issue by imrecsoka** [yaser01/mkv-muxing-batch-gui#79]
Hello, not sure how to request a feature or additional options in the application, but i just came across something that might be useful, please if possible.

To add subfolders within the Video Source Folder.
To have an option for Videos Destination Folder, to allow muxed files to reside in the same folder as source with added _new.mkv or even overwrite.

Thank you , hope it makes sense

**Comment by yaser01** [comment]
I will work on this :D

**Comment by yaser01** [comment]
For the first suggestion it won't be added since it's not worth the complexity that will be added to the gui.
For the second suggestion try 2.4 Update :D
