### ISSUE TITLE
.mp4 files, not able to select discard certain tracks based on meta data (language)

### ISSUE THREAD

**Issue by popy2k14** [yaser01/mkv-muxing-batch-gui#81]
Nice app!
Just a small feature request:
Tried it with mkv's and it's working flawlessly.
Sadly with .mp4 files, i can't select the discarding options in the muxing tab, based on languages.
They are grayed out.

Is it possible to support the feature on mp4 files?

thx

**Comment by Jorchking** [comment]
I have the same problem.

**Comment by eddilara** [comment]
until he adds this
do this..
run the mp4 files though mkvtools to output a mkv....then you can edit those files with this tool

**Comment by popy2k14** [comment]
thx for the hint

**Comment by yaser01** [comment]
@popy2k14 @Jorchking 
I want more information on this 
Can MP4 Container have multi tracks for subtitle and  audio?
Can you provide me with example?

**Comment by yaser01** [comment]
@eddilara Thanks for the files bro will take time to download ^‿^ [due to super fast internet in syria]
@popy2k14 I will try to figure this out will keep you up to date with this

**Comment by yaser01** [comment]
@eddilara @popy2k14 
Do you know any extensions besides .mkv and .mp4 can have multi tracks?

**Comment by popy2k14** [comment]
@yaser01 thx for looking into this. Searched a list for container formats which supports multiple streams, but sadly not found an complete. I think MKV and MP4  are the most common ones.

**Comment by eddilara** [comment]
ogm does...tho no one uses that anymore

**Comment by yaser01** [comment]
Thanks @eddilara @popy2k14
Do you have any example for any extension you said [file with multi track]?

**Comment by popy2k14** [comment]
@yaser01 in think the most common/used container formats used today are MP4 & MKV.

**Comment by yaser01** [comment]
Me too @popy2k14 
but extra wait won't be so bad

**Comment by yaser01** [comment]
Try 2.4 Update :D

**Comment by popy2k14** [comment]
@yaser01 thx for the update.
Tested with this: https://cdn.media.ccc.de/congress/2019/h264-hd/36c3-11235-eng-deu-fra-36C3_Infrastructure_Review_hd.mp4
mp4 multi audio sample and just keeped german audio track.

It worked and removed the other two audio tracks, but the default audio track was set to none/deactivated.
So when opening with VLC it had no sound until i selected the german audio track.

Not a big deal, but just want to let you know.

thx again

**Comment by yaser01** [comment]
You are welcome man :D
You can just use `Make This Audio Default` in the muxing tab and select the german audio track

**Comment by popy2k14** [comment]
@yaser01 thx for coming back to me.
I have set this, but it does not work, VLC does'nt select the first audio  track.

![image](https://github.com/yaser01/mkv-muxing-batch-gui/assets/6324597/943f9d38-9e3d-4374-bcd1-77967afcdcbe)

Also when i select "Make This Audio Default" the setting does'nt stick.
On next application start the setting is gone.

Can you please reproduce this with the sample video above?

thx

**Comment by yaser01** [comment]
can you share the mediainfo before and after ?

**Comment by popy2k14** [comment]
@yaser01 will do so when i have an actual issue with an movie. That's just an test video.

thx

**Comment by yaser01** [comment]
> Also when i select "Make This Audio Default" the setting does'nt stick.
On next application start the setting is gone.

This feature hasn't been added yet.. the preset setting will have updates for sure..

**Comment by yaser01** [comment]
@popy2k14 
Still waiting for the mediainfo :D

**Comment by popy2k14** [comment]
@yaser01 just found time to make the media info files (See attached).
It seems the tool is making all correctly and the only audio track is default.

But VLC is selecting "no audio track" default.
When i open the same file with windows default "Movies & TV" app, audio selected fine.

Seems like an VLC issue rather than mkv muxing batch gui issue.

Sorry for wasting your time.

[mediainfo_after_mp4_to_mkv.txt](https://github.com/yaser01/mkv-muxing-batch-gui/files/13991571/mediainfo_after_mp4_to_mkv.txt)
[mediainfo_before_mp4_to_mkv.txt](https://github.com/yaser01/mkv-muxing-batch-gui/files/13991572/mediainfo_before_mp4_to_mkv.txt)

PS.: will be testing this again, when i actually have an mp4 file which i want strip and convert to mkv :-)
