### ISSUE TITLE
[Feature request] Set forced in mux settings window

### ISSUE THREAD

**Issue by Samo99** [yaser01/mkv-muxing-batch-gui#83]
Hi

Would you please add an option to force certain audio or subtitle that's already existing in the mkv?

**Comment by eddilara** [comment]
you can already
in the mux window...double click the set default box

**Comment by Samo99** [comment]
> you can already in the mux window...double click the set default box

I know that there is default checkbox but that will not be effective if you set a favorite language in your player so the force option is better

**Comment by eddilara** [comment]
theres 2 settings for the check box...default and forced...if you set it to checkmark...its forced
a better feature request would be make this more clear in the gui so people know this

**Comment by Samo99** [comment]
> theres 2 settings for the check box...default and forced...if you set it to checkmark...its forced a better feature request would be make this more clear in the gui so people know this

I think you didn't read my request correctly, what i asked for was for an option in the mux settings tab not the audios tab to force an existing audio in an mkv.

**Comment by eddilara** [comment]
thats what I said...
in the mux tab....those boxes have 2 settings...default and forced

**Comment by Samo99** [comment]
> thats what I said... in the mux tab....those boxes have 2 settings...default and forced

Where?

![التقاط](https://user-images.githubusercontent.com/12115578/224941116-2b4ff67c-c0e3-403f-8da6-469c848e58d3.PNG)

**Comment by eddilara** [comment]
make this audio default
make this sub default

**Comment by Samo99** [comment]
> will not be effective if you set a favorite language in your player so the force option is better

Onec you said there is a force option and after back and forth you realized it's not there and now you say use the make audio default?

I told you from the beginning that "it will not be effective if you set a favorite language in your media player so the force option is better"

**Comment by ThePhantom00** [comment]
@Samo99 
![image_2023-05-08_215749565](https://user-images.githubusercontent.com/42273394/236908953-044ec7fe-c4cf-4103-b71a-5dd6a5349a4e.png)

**Comment by Samo99** [comment]
> @Samo99 ![image_2023-05-08_215749565](https://user-images.githubusercontent.com/42273394/236908953-044ec7fe-c4cf-4103-b71a-5dd6a5349a4e.png)

Now that's what i'm talking about.
Thank you sir.
