### ISSUE TITLE
Some new features

### ISSUE THREAD

**Issue by Shishiaha** [yaser01/mkv-muxing-batch-gui#84]
I would like to propose some new features that could be great : 

- Allow to mux even if no parameters are selected. (Sometimes a file needs to be remuxed to refresh some metadata)
- Give the opportunity to rename already existing audio and subtitle tracks per language with custom string. For exemple, all english tracks => "English Track".
- The one above could also be useful to default a track by its language or name for more consistency.
- Allow to make "none" subtitle default when not selecting one but checking the checkbox.

Thanks for this tool, really nice one. I hope to see you around as it seems you are off since a long time.

**Comment by eddilara** [comment]
1....can easy do this in a batch with mkvtools
2...already on the feature request list
3...already on the feature request list by the cmd line arguments request ...can also be done by JMkvpropedit for now until he adds the feature
4....you don't want a default sub....this can also be done by JMkvpropedit for now

**Comment by Shishiaha** [comment]
Thanks for your answer, but : 

1 - If i want to batch with mkvtools i would not use this.
3 & 4 - JMkvpropedit is a pain to use as it does not detect tracks and has to set every settings track by track, wich is bad if you have 30+ tracks, or changing number of tracks in your batch. While in this project, it would be pretty easy to add it when checking the default sub option and letting it empty (like it works for audio tracks).

Anyway, i can also just fork this project and make ajustements myself to it, not really an issue, but i already work on C# these days and it would be less efficient.

For the first one, the first is pretty easy, just check attachments options, and check delete attachments. It allows to bypass restriction even if there is no attachments.

**Comment by yaser01** [comment]
1. I will add this 
2. will look into this
3. also will look into this
2 & 3 are manipulating old tracks this need a lot do to make it easy and useful as a batch
4 probably will add this soon
this doesn't mean i won't work on 2&3  but i want to give it a time to think with easy and nice way to change setting for old tracks so the app won't have complex gui

**Comment by yaser01** [comment]
@Shishiaha  About (3):
Do you mean you want to set an old track [by its language or name ] to be default ?

**Comment by Shishiaha** [comment]
Hey  @yaser01 , Thank you for responding back.

Yes, having an option that will default the first track of a defined language on every file of the batch, or if selected but no language selected, then just showing the default message in the box "no default subtitle" if empty, and then remove any default track for subtitles (passing no to default & forced to all), versus passing no to all except the language selected in the other case.

We can imagine a box checker "Changing default sub behavior", that once checked gives access to a drop-down list, with the default "No default subtitle", and then expand with all language (detected on the first file or premade) and select one if needed to make it default on all the batch.

**Comment by yaser01** [comment]
Thanks for the long explanation , I think it's already in 2.3
![image](https://github.com/yaser01/mkv-muxing-batch-gui/assets/52576632/89804c88-003e-4e94-bd09-d38e4ecc30c0)

**Comment by yaser01** [comment]
Try 2.4 Update :D
