### ISSUE TITLE
Couldn’t run the linux version

### ISSUE THREAD

**Issue by WaseemMuadi** [yaser01/mkv-muxing-batch-gui#85]
So long story short is that I don’t know how to run the linux version app, I did my research but found nothing..
can you explain how to run this app or make a deb setup file? there is no instructions to install the app.

Many thanks.

**Comment by yaser01** [comment]
There in no installion needed
just download the tar.gz file [link](https://github.com/yaser01/mkv-muxing-batch-gui/releases/download/2.3/MKV.Muxing.Batch.GUI.x64.v2.3.Linux.Portable.tar.gz) and then open MKV Muxing Batch GUI File

**Comment by WaseemMuadi** [comment]
After sometime I decided to fresh reinstall Ubuntu on my PC, now the app works and I did unzip it, but when I try to add a language to the supported subtitle languages and reopen the app it doesn’t appear, and when I press on the output location button  the app closes by itself

My system is Ubuntu 22.04.3LTS x64

**Comment by popy2k14** [comment]
> After sometime I decided to fresh reinstall Ubuntu on my PC, now the app works and I did unzip it, but when I try to add a language to the supported subtitle languages and reopen the app it doesn’t appear, and when I press on the output location button the app closes by itself
> 
> My system is Ubuntu 22.04.3LTS x64

Exact same issue here. Any chance to get an proper linux version?
My issues are:

- It does'nt remember the settings (like language)
- mkvmerge missing popup appears on start
- when i press on ouput folder the app closes

thx

**Comment by yaser01** [comment]
@popy2k14 do you mean the python version works good and the problem only in the executable linux version?

**Comment by popy2k14** [comment]
@yaser01 yes, the issues from my previous post are only with the linux version.

**Comment by yaser01** [comment]
New Version 2.4 is more linux friendly, and read [this](https://github.com/yaser01/mkv-muxing-batch-gui/tree/2.4?tab=readme-ov-file#for-linux-users) if any problem happen again

**Comment by popy2k14** [comment]
thx a lot for the update.
Sadly, i cant currently test it because i am back to windows.

**Comment by yaser01** [comment]
@popy2k14 NP Have a nice day :D
