### ISSUE TITLE
Changing video and audio names 

### ISSUE THREAD

**Issue by TimucinPusat** [yaser01/mkv-muxing-batch-gui#87]
I tried a few programs but this is the best among them. So I removed them and decided to use this. So far so good. Thank you a lot. I have a few questions: 

1. Do I need to have MKVToolNix installed to use this program? 
2. Is there a loss of quality in the exported video and audio files after processing with this program? In other words, is there any interference with the quality of the original audio and video files? 
3.  I coudn't see the option to change or remove the video and audio names before muxing. How to do it? 
4. After video merging, the exported file is about 100 mb smaller than the original video file. For this reason, although the before and after sizes of the files look the same on the program, it is not the same when viewed through windows, there is a difference of about 100mb. When I do the same with MKVToolNix, the size is still reduced by the amount I mentioned. What is the reason for this? 
5. I didn't see a button or option to restart the multiplexing process (after freeing up disk space) when multiplexing is stopped because there is not enough space on the disk.

**Comment by eddilara** [comment]
1...yes
2 no
3 not a feature added yet....but its on the list....you can use JMkvpropedit until this feature is added
4.. thats pretty normal if the file you had before was an older files....mkvtools optimizes the file headers and such ...100mb does seem a bit much tho......use mediainfo tool to see the file differences
5...haven't added that yet....also on the list

**Comment by TimucinPusat** [comment]
> 

Thank you dude for your replies. As far as I remember the file size was about 5-10 GB, so 100mb is accebtable I think. 

Yes, as you said, when I was researching, I coincidentally saw that there was a program called JMkvpropedit and I started using it before your this reply:) 

It would be good if you add this feature and the feature I mentioned below, that is, the ability to restart the process if it stops for any reason. Also, the program doesn't stop when you pause the process, it continues to do its job, for your information:) Other than that it is a very useful program. It made my work very easy. Thank you very much. But it would be much better if you improve it.

**Comment by eddilara** [comment]
I have a feeling the original dev for this program died since he lives in syria...

**Comment by yaser01** [comment]
1- not really what OS you use?
2- no totally not touching the source files
3- you want to change old video-audio track name or file name ? 
4- this can happen due to multi reasons as @eddilara mentioned above or even the video can contain a bad blocks which mkvmerge [from mkvtoolnix] will drop it but if check abort on errors option you will get notify when this happen
5- will look into this 
thanks for the suggestion and thanks for @eddilara for his big assist 
Have a nice day you both :D

**Comment by TimucinPusat** [comment]
حمدا لله على سلامة ياسر (وهو اسم ابني من أحب الأسماء إلي) 
1. Windows 11 the latest version.
3. Yes like we can do with JMkvpropedit as eddilara suggested. I want to change audio, subtitles' names or languages. 
4. But I have many TV shows about (30TB) whenever I tried it with them there is a drop in file size almost always. 
5. Yes, the pause button does not work in the program. For example, you want to take a break, you press pause, but it still continues. In the same way, let's say your hdd is full, you will empty it and continue again, but it definitely does not stop. Therefore, in such cases, it is necessary to close the program completely, relocate all files and restart it again. 

Finally, your program is very good, it works great. I don't use MKVtoolnix anymore, it was too laborious. This, your program is very practical. But it would be great if you could fix these things and make some more improvements. Thank you very much.

**Comment by yaser01** [comment]
الله يسلمك يارب و اياكم الحمدلله و حمى الله ابنك ورعاه
1- did you try to run the app after uninstall mkvtoolnix?
2- ok i will look into this as it been requested lot of times
3- did you compare MedaInfo of both input and output videos is there something missing ? [The muxing is totally a lossless operation but just to make sure why there is reduce in file's size]
4- i think you mean the pause file doesn't pause current muxing [it just wait for current muxing job to end and then pause]? or it's not stooping anything?
Thanks for the nice feedback and i am proud of this words :D

**Comment by TimucinPusat** [comment]
شكرا لك أخي
1. no I didn't try it, but I'll
2. great
3. I'll compare the sizes when I use your program with mediainfo. it's good that it's lossless.
4. Actually, I didn't wait it to finish its job till the end of the current muxing. It may pause after finishing its job. I don't know. I have to try. I thought it doesn't work completely. 
You welcome.

**Comment by yaser01** [comment]
Very Good
let me informed about 1 & 3
4- yes the pause button actually wait for current muxing job to end and then pause i will see if i can do it to abort current job and then pause

**Comment by yaser01** [comment]
Try 2.4 Update :D
