### ISSUE TITLE
Bug in subtitle window

### ISSUE THREAD

**Issue by Samo99** [yaser01/mkv-muxing-batch-gui#91]
Hey yaser

I found a weird bug in the subtitle window, when you select a subtitle and press move sub to the top the first subtitle that was in that place jumps to be the last one instead of becoming number 2.

**Comment by Samo99** [comment]
> I will fix this tbh, i didn't think it is a bug [I choose this way of action] but after some thinking now your way is better Thanks for letting me know this :D

Thanks to you :)

**Comment by yaser01** [comment]
Fixed in 2.4 Update :D
