### ISSUE TITLE
Processing recursive folders

### ISSUE THREAD

**Issue by psonnosp** [yaser01/mkv-muxing-batch-gui#93]
Just found this little gem of a program that sure makes my life a bit easier.

What would be sweet though is if it could take care of files in multiple folders at once.
I have multiple files in separate folders that I process and place the result in a corresponding folder tree but on a different disk.
So would be great if I could just set the source to disk one and the program would recursively find all files and process/place them in the same folder structure as the source but on another disk.

Would that be possible or is there any other program, with a GUI, around already that does this?

**Comment by eddilara** [comment]
so you want the program basically just to find all the video files in a directory and under the directory

you realize that might get complicated with loading subtitles for those files right....unless he can figure out a way to match the video file name with the subtitle name...provided they are named the same

**Comment by yaser01** [comment]
Thanks for your suggestion 
But this gonna be very complicated to handle (there is so many ways that this could be go wrong)
Subtitles/Audios matching would be a nightmare with the current setting 
And i won't do it so they have to be same as video files names, this is the opposite of what `MKV Muxing Batch GUI` created for.

**Comment by psonnosp** [comment]
Think I did a bad job explaining.
With processing I mean clean already existing mkv's (or re-muxing if that's a word?) from everything except audio and video, there are no matching of external audio/subtitles and such to be done.
But maybe it still is "out of bounds" for the intent of the program so I'll have to stick with processing single folders one by one.
If so, thanks for your time anyway.

**Comment by eddilara** [comment]
thats a little easier to do if all you wanna do is remove subtitles and attachments..and only have 1 language audio
