### ISSUE TITLE
"Remember last settings" or "setting-profiles"

### ISSUE THREAD

**Issue by mpek** [yaser01/mkv-muxing-batch-gui#94]
At least the first would be very helpful and perhaps quicker to implement? 

Let's say you want to add new sutitles from external and define two tracks with one is the "new" default and the second is a forced type, everything after the first track always has to be set again after a restart of MMBG. 

With "Remember last settings" you would have the chance to find the right output quicker, when restarting MMBG. 
With "setting-profiles" you could quickly change export-settings, because you already defined them previously -> constantly good resutls.

Thank you for this nice approach to batch process MKV without Java.

**Comment by yaser01** [comment]
Thanks for the long explanation but i really didn't fully understand what you are talking about 
I would appreciate it if you give me example with screenshots [maybe]?
Thanks again :D

**Comment by mpek** [comment]
If you define a second subtitle in Subtitle Tab. This setting is gone after you restart and it could be useful MMBG remembers last settings used ("Remember last settings"). 
The best would be to be able to define settings and being able to recall them ( "setting-profiles").

**Comment by yaser01** [comment]
Thanks again for the perfect explanation but if it's only for [number of subtitle] it's just a a button click [not that big effort tbh]
There is already a preset in the setting dialog like default directories and so on..
I can't make it all be saved because some setting depends on current files and when you close an re-open MMBG those files could be gone and make extra [unneeded] trouble
If you have a better idea, tell me :D
Thanks again and have a nice day.

**Comment by mpek** [comment]
Subtitle tab was an example for every other tab's settings, that you have to adjust every time starting MMBG. 
If you don't think there is an advantage, there is nothing I can do to convince you :)

**Comment by yaser01** [comment]
I will look into this as a 'remember last settings' option :D

**Comment by mpek** [comment]
Thank you for considering. I look forward to it 🎉

**Comment by yaser01** [comment]
Added Presets, it's not exactly as you mentioned, but it will get updates in the future. 
for now try 2.4 Update :D

**Comment by mpek** [comment]
I see, you can define now different presets for different source directories, much nicer! Thank you.
