### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Darkmaster006** [yaser01/mkv-muxing-batch-gui#98]
Hello there! First of all, thank you very very much for this software! It has been invaluably helpful in helping me mux especially different audios into the same show in batch, so thank you very much for this! As for the feature request, what I think would be very useful is to be able to change the settings, order, etc. of the already-known tracks. For example, let's say I have a video with two audios (Eng and Spa) and two subtitles (Eng and Spa) and let's say both English tracks are first, so what I would like to do is change the order so that the Spanish tracks are first, for example. As it stands now, you can force the track to be "forced first" but in the actual order it is not first, so some players (like on TVs) will not recognise it as they use the first audio/subtitle given. Or, in any case, have a menu which has all audios (both the ones being added and the ones already on the file) and also subtitles, so that we can change the order as we wish. Think this can be done? Thank you!

**Comment by eddilara** [comment]
this would be a useful feature
would be possible to do this with the cmd line feature request as well
tho a gui option would be better

**Comment by yaser01** [comment]
Thanks for the very well explaining  
I am already working on this feature but i can't make it to have both old and new(added) tracks because input files may not be the same structure so added tracks may have different ids,and you may say so how to show old tracks even files may differs.... you will see :D
Thanks again and stay tuned for next update .. in the next month ... or the next one :D

**Comment by Darkmaster006** [comment]
> Thanks for the very well explaining I am already working on this feature but i can't make it to have both old and new(added) tracks because input files may not be the same structure so added tracks may have different ids,and you may say so how to show old tracks even files may differs.... you will see :D Thanks again and stay tuned for next update .. in the next month ... or the next one :D

Thank you! No worries, take your time!

**Comment by yaser01** [comment]
Try 2.4 Update :D

**Comment by Darkmaster006** [comment]
> Try 2.4 Update :D

Thank you!!
